service: aws-python-http-api
frameworkVersion: '4'

provider:
  name: aws
  runtime: python3.13
  environment:
    APP_DOMAIN: ${param:domain}
    KEY: ${param:key}
functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
